spring.application.name=StudyRoomBackend
spring.datasource.url=jdbc:mysql://localhost:3306/studyroom?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=20226829
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis 配置
mybatis.type-aliases-package=com.example.studyroom.po
# 开启驼峰命名映射（数据库 user_id → Java userId）
mybatis.configuration.map-underscore-to-camel-case=true
# 打印 SQL 日志（开发阶段）
logging.level.com.example.studyroom.mapper=debug

server.port=8088