spring.application.name=StudyRoomBackend
spring.datasource.url=jdbc:mysql://localhost:3306/studyroom?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=20226829
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.example.studyroom.po

server.port=8088